=== MichaelCook/setwin/schema.json
{
  "$id": "http://www.waxrat.com/setwin",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "JSON schema for Setwin's configuration file setwin.json",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "wmclass": {
        "$comment": "Match against the window's window manager class",
        "type": "string",
        "format": "regex"
      },
      "title": {
        "$comment": "Match against the window's title",
        "type": "string",
        "format": "regex"
      },
      "workspace": {
        "$comment": "Place this window on the specified workspace (0-based), or -1 to be on all workspaces",
        "type": "integer",
        "minimum": -1
      },
      "x": {
        "$comment": "Place this window at the specified X-coordinate, or negative means relative to the monitor width",
        "type": "integer"
      },
      "y": {
        "$comment": "Place this window at the specified Y-coordinate, or negative means relative to the monitor height",
        "type": "integer"
      },
      "width": {
        "$comment": "Set this window's height; negative means relative to the monitor width; 0 to maximize",
        "type": "integer"
      },
      "height": {
        "$comment": "Set this window's width; negative means relative to the monitor height; 0 to maximize",
        "type": "integer"
      },
      "max_match": {
        "$comment": "Apply this rule no more than this many times",
        "type": "integer",
        "minimum": 1
      },
      "above": {
        "$comment": "Mark this window to always be above other windows",
        "type": "boolean"
      }
    },
    "additionalProperties": false
  }
}

=== MichaelCook/setwin/setwin.json
[
    {
        "wmclass": "^QtPoll$",
        "workspace": -1,
        "x": 0,
        "y": -33
    },
    {
        "wmclass": "^Emacs$",
        "title": "@porcupine|@ursine",
        "workspace": 0,
        "x": 0,
        "y": 0,
        "width": 920,
        "height": -60
    },
    {
        "wmclass": "^Emacs$",
        "title": "@kilo",
        "workspace": 1,
        "x": 0,
        "y": 0,
        "width": 920,
        "height": -60
    },
    {
        "wmclass": "^QtEdPod$",
        "workspace": 3,
        "width": 0,
        "height": 0
    },
    {
        "wmclass": "^gnome-terminal-server$",
        "title": "^(porcupine|ursine):",
        "workspace": 0,
        "x": 925,
        "y": 27,
        "width": 1000,
        "height": -20
    },
    {
        "wmclass": "^gnome-terminal-server$",
        "title": "^wally:",
        "workspace": -1,
        "x": 50,
        "y": 50,
        "width": 900,
        "height": 800
    },
    {
        "wmclass": "^gnome-terminal-server$",
        "title": "^kilo:",
        "workspace": 1,
        "x": 925,
        "y": 27,
        "width": 1000,
        "height": -20
    },
    {
        "wmclass": "^Google-chrome$",
        "workspace": 2,
        "width": 0,
        "height": 0
    },
    {
        "wmclass": "^libreoffice-calc$",
        "workspace": 4,
        "x": 978,
        "y": 24,
        "width": 940,
        "height": -32
    }
]
